version: '3.8'

services:
  web:
    build: .
    container_name: django_server_app
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: python myproject/manage.py runserver 0.0.0.0:8000

